name: flutter_two_octaves_piano
description: A new Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - sax/

  module:
    androidX: true
    androidPackage: com.example.flutter_two_octaves_piano
    iosBundleIdentifier: com.example.flutterTwoOctavesPiano
